import re

CLI_PATH = '/Users/binarygeotech/Projects/opensource/omni-queue/packages/cli/src/index.ts'

HELPERS = r"""
function parseFlags(flagArgs: string[]): Record<string, string> {
  const flags: Record<string, string> = {};
  for (const arg of flagArgs) {
    const match = arg.match(/^--([^=]+)=?(.*)$/);
    if (match) flags[match[1]!] = match[2] ?? 'true';
  }
  return flags;
}

function ensureOmniRuntime(cwd: string): string {
  const dir = path.join(cwd, '.omni', 'runtime');
  fs.mkdirSync(dir, { recursive: true });
  return dir;
}

function generateIsolationWorkerShim(): string {
  const lines = [
    '// Auto-generated by omni gen isolation. Do not edit.',
    "import { createRequire } from 'node:module';",
    "import { pathToFileURL } from 'node:url';",
    '',
    'const require = createRequire(import.meta.url);',
    "const workerPath = require.resolve('@omni-queue/core/dist/libs/isolation-worker');",
    'await import(pathToFileURL(workerPath).href);',
    '',
  ];
  return lines.join('\n');
}

function writeTempTsconfig(cwd: string, definitionsDir: string, outDir: string): string {
  const omniDir = path.join(cwd, '.omni');
  fs.mkdirSync(omniDir, { recursive: true });
  const tsconfigPath = path.join(omniDir, 'tsconfig.gen.json');
  const relativeDefsDir = path.relative(omniDir, definitionsDir).split(path.sep).join('/');
  const relativeOutDir = path.relative(omniDir, outDir).split(path.sep).join('/');

  const config: Record<string, unknown> = {
    compilerOptions: {
      outDir: relativeOutDir,
      noEmit: false,
      declaration: false,
      sourceMap: false,
    },
    include: [`${relativeDefsDir}/**/*.ts`],
  };

  if (fs.existsSync(path.join(cwd, 'tsconfig.json'))) {
    config['extends'] = '../tsconfig.json';
  } else {
    const co = config['compilerOptions'] as Record<string, unknown>;
    co['target'] = 'ES2022';
    co['module'] = 'NodeNext';
    co['moduleResolution'] = 'NodeNext';
    co['esModuleInterop'] = true;
  }

  fs.writeFileSync(tsconfigPath, JSON.stringify(config, null, 2) + '\n', 'utf8');
  return tsconfigPath;
}

function runTsc(tsconfigPath: string): Promise<void> {
  return new Promise((resolve, reject) => {
    const child = spawn('npx', ['tsc', '--project', tsconfigPath], {
      cwd: path.dirname(path.dirname(tsconfigPath)),
      stdio: 'inherit',
      shell: process.platform === 'win32',
    });
    child.on('exit', (code) => {
      if (code === 0) { resolve(); return; }
      reject(new Error(`tsc exited with code ${code ?? 'unknown'}`));
    });
    child.on('error', reject);
  });
}

"""

with open(CLI_PATH) as f:
    content = f.read()

lines = content.split('\n')
print(f'Total lines: {len(lines)}')

# Find the end of resolveRuntimeDir (first occurrence of a closing brace line after line 170)
# and the start of runGenerateIsolation
resolve_end_idx = None
run_gen_idx = None

for i, line in enumerate(lines):
    if i > 170 and re.match(r'^}$', line) and resolve_end_idx is None:
        resolve_end_idx = i
    if 'async function runGenerateIsolation' in line:
        run_gen_idx = i
        break

print(f'resolveRuntimeDir ends at line {resolve_end_idx + 1} (0-indexed: {resolve_end_idx})')
print(f'runGenerateIsolation starts at line {run_gen_idx + 1} (0-indexed: {run_gen_idx})')

# Find the FIRST occurrence of "main().catch"
main_catch_idx = None
for i, line in enumerate(lines):
    if 'main().catch' in line:
        main_catch_idx = i
        break

print(f'First main().catch at line {main_catch_idx + 1} (0-indexed: {main_catch_idx})')

# Find the SECOND occurrence of "async function main()"
main_fn_indices = [i for i, l in enumerate(lines) if 'async function main()' in l]
print(f'async function main() at lines: {[i+1 for i in main_fn_indices]}')

# Take: lines 0..resolve_end_idx (inclusive) + HELPERS + lines run_gen_idx..main_catch_idx-1 + main().catch block
head = lines[:resolve_end_idx + 1]
gen_section = lines[run_gen_idx:main_catch_idx]

main_catch_block = '\nmain().catch((error) => {\n  console.error(error instanceof Error ? error.message : error);\n  process.exitCode = 1;\n});\n'

final_lines = '\n'.join(head) + '\n' + HELPERS + '\n'.join(gen_section) + main_catch_block

with open(CLI_PATH, 'w') as f:
    f.write(final_lines)

print(f'Written. Final lines: {final_lines.count(chr(10))}')

# verify no duplicate async function main
verify_lines = final_lines.split('\n')
mains = [i+1 for i, l in enumerate(verify_lines) if 'async function main()' in l]
print(f'async function main() now at lines: {mains}')
