// Auto-generated by omni gen isolation. Do not edit.
import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';

const require = createRequire(import.meta.url);
const workerPath = require.resolve('@omni-queue/core/dist/libs/isolation-worker');
await import(pathToFileURL(workerPath).href);
