import fs from 'node:fs';
import path from 'node:path';
import { spawn } from 'node:child_process';

export async function runOmni(omniArgs: string[]) {
	const command = omniArgs[0];
	const subcommand = omniArgs[1];

	if (command === 'gen' && subcommand === 'isolation') {
		await runGenerateIsolation(omniArgs.slice(2));
		return;
	}

	printOmniUsage();
	process.exitCode = command ? 1 : 0;
}

function printOmniUsage() {
	console.log('Omni-Queue Generator CLI');
	console.log('');
	console.log('Usage:');
	console.log('  omni gen isolation [--dir=./src/definitions]');
}

function parseFlags(flagArgs: string[]): Record<string, string> {
	const flags: Record<string, string> = {};
	for (const arg of flagArgs) {
		const match = arg.match(/^--([^=]+)=?(.*)$/);
		if (match) flags[match[1]!] = match[2] ?? 'true';
	}
	return flags;
}

function ensureOmniRuntime(cwd: string): string {
	const dir = path.join(cwd, '.omni', 'runtime');
	fs.mkdirSync(dir, { recursive: true });
	return dir;
}

function generateIsolationWorkerShim(): string {
	return [
		'// Auto-generated by omni gen isolation. Do not edit.',
		"import { createRequire } from 'node:module';",
		"import { pathToFileURL } from 'node:url';",
		'',
		'const require = createRequire(import.meta.url);',
		"const workerPath = require.resolve('@omni-queue/core/libs/isolation-worker');",
		'await import(pathToFileURL(workerPath).href);',
		'',
	].join('\n');
}

function writeTempTsconfig(cwd: string, definitionsDir: string, outDir: string): string {
	const omniDir = path.join(cwd, '.omni');
	fs.mkdirSync(omniDir, { recursive: true });
	const tsconfigPath = path.join(omniDir, 'tsconfig.gen.json');
	const relativeDefsDir = path.relative(omniDir, definitionsDir).split(path.sep).join('/');
	const relativeOutDir = path.relative(omniDir, outDir).split(path.sep).join('/');

	const config: Record<string, unknown> = {
		compilerOptions: {
			outDir: relativeOutDir,
			noEmit: false,
			declaration: false,
			declarationMap: false,
			emitDeclarationOnly: false,
			sourceMap: false,
		},
		include: [`${relativeDefsDir}/**/*.ts`],
	};

	if (fs.existsSync(path.join(cwd, 'tsconfig.json'))) {
		config.extends = '../tsconfig.json';
	} else {
		Object.assign(config.compilerOptions as object, {
			target: 'ES2022',
			module: 'NodeNext',
			moduleResolution: 'NodeNext',
			esModuleInterop: true,
		});
	}

	fs.writeFileSync(tsconfigPath, JSON.stringify(config, null, 2) + '\n', 'utf8');
	return tsconfigPath;
}

function runTsc(tsconfigPath: string): Promise<void> {
	return new Promise((resolve, reject) => {
		const child = spawn('npx', ['tsc', '--project', tsconfigPath], {
			cwd: path.dirname(path.dirname(tsconfigPath)),
			stdio: 'inherit',
			shell: process.platform === 'win32',
		});
		child.on('exit', (code) => {
			if (code === 0) {
				resolve();
				return;
			}
			reject(new Error(`tsc exited with code ${code ?? 'unknown'}`));
		});
		child.on('error', reject);
	});
}

export async function runGenerateIsolation(flagArgs: string[]) {
	const cwd = process.cwd();
	const flags = parseFlags(flagArgs);
	const definitionsDir = path.resolve(cwd, flags.dir ?? './src/definitions');

	if (!fs.existsSync(definitionsDir)) {
		const rel = path.relative(cwd, definitionsDir);
		console.log(`Definitions directory not found: ${definitionsDir}`);
		console.log('');
		console.log('Create your first definition file:');
		console.log('');
		console.log(`  mkdir -p ${rel}`);
		console.log('');
		console.log(`  # ${rel}/main.ts`);
		console.log("  import { defineIsolation } from '@omni-queue/core';");
		console.log("  import { MyJob } from '../jobs/my-job';");
		console.log('');
		console.log('  export const { getRegistry, getPlugins } = defineIsolation({');
		console.log('    jobs: [MyJob],');
		console.log('    plugins: [],');
		console.log('  });');
		console.log('');
		console.log('Then re-run: omni gen isolation');
		return;
	}

	const definitionFiles = fs
		.readdirSync(definitionsDir)
		.filter((file) => file.endsWith('.ts'))
		.map((file) => path.join(definitionsDir, file));

	if (definitionFiles.length === 0) {
		console.log(`No .ts files found in ${definitionsDir}`);
		return;
	}

	const omniRuntimeDir = ensureOmniRuntime(cwd);
	const tsconfigPath = writeTempTsconfig(cwd, definitionsDir, omniRuntimeDir);
	const names = definitionFiles.map((file) => path.basename(file, '.ts'));

	console.log(
		`Compiling ${definitionFiles.length} definition(s): ${names.join(', ')} -> ${path.relative(cwd, omniRuntimeDir)}/`
	);

	try {
		await runTsc(tsconfigPath);
	} finally {
		fs.rmSync(tsconfigPath, { force: true });
	}

	const shimPath = path.join(omniRuntimeDir, 'isolation-worker.js');
	fs.writeFileSync(shimPath, generateIsolationWorkerShim(), 'utf8');
	console.log(`Generated: ${shimPath}`);
	console.log('');
	console.log('Isolation runtime ready in .omni/runtime/');
	console.log('');
	console.log('Use in your worker config:');
	for (const name of names) {
		console.log(`  const ${name}Modules = resolveRuntimeModules('${name}');`);
	}
}
